//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RssSyndicationFeed.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RssSyndicationFeed.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;atom:link href=&quot;http://news.bnt.bg/bg/rss/news.xml&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot; /&gt;
        ///    &lt;title&gt;БНТ Новини&lt;/title&gt;
        ///    &lt;link&gt;http://news.bnt.bg/&lt;/link&gt;
        ///    &lt;description&gt;Новини от Българска национална телевизия&lt;/description&gt;
        ///    &lt;language&gt;bg&lt;/language&gt;
        ///    &lt;lastBuildDate&gt;Sat, 16 Sep 2017 16:25:05 +0300&lt;/lastBuildDate&gt;
        ///    &lt;item&gt;
        ///      &lt;title&gt;Откриха бюстове и картини на Хитле [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BNT {
            get {
                return ResourceManager.GetString("BNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;title&gt;Капитал - България&lt;/title&gt;
        ///    &lt;link&gt;http://www.capital.bg/rss/?rubrid=2249&lt;/link&gt;
        ///    &lt;description&gt;&lt;/description&gt;
        ///    &lt;language&gt;bg&lt;/language&gt;
        ///    &lt;image&gt;
        ///      &lt;url&gt;http://www.capital.bg/i/6/capital-rss.gif&lt;/url&gt;
        ///      &lt;urlITunes&gt;http://www.capital.bg/i/capital_logo.png&lt;/urlITunes&gt;
        ///      &lt;title&gt;Capital.bg&lt;/title&gt;
        ///      &lt;link&gt;http://www.capital.bg&lt;/link&gt;
        ///      &lt;width&gt;144&lt;/width&gt;
        ///      &lt;height&gt;26&lt;/height&gt;
        ///    &lt;/im [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CapitalBG {
            get {
                return ResourceManager.GetString("CapitalBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; media=&quot;screen&quot; href=&quot;/~d/styles/rss2full.xsl&quot;?&gt;&lt;?xml-stylesheet type=&quot;text/css&quot; media=&quot;screen&quot; href=&quot;http://rss.cnn.com/~d/styles/itemcontent.css&quot;?&gt;&lt;rss xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:content=&quot;http://purl.org/rss/1.0/modules/content/&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot; xmlns:media=&quot;http://search.yahoo.com/mrss/&quot; version=&quot;2.0&quot;&gt;&lt;channel&gt;&lt;title&gt;&lt;![CDATA[CNN.com - RSS Channel - App International Edition]]&gt;&lt;/title&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CNN {
            get {
                return ResourceManager.GetString("CNN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; media=&quot;screen&quot; href=&quot;/~d/styles/rss2full.xsl&quot;?&gt;&lt;?xml-stylesheet type=&quot;text/css&quot; media=&quot;screen&quot; href=&quot;http://rss.cnn.com/~d/styles/itemcontent.css&quot;?&gt;&lt;rss xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:content=&quot;http://purl.org/rss/1.0/modules/content/&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot; xmlns:media=&quot;http://search.yahoo.com/mrss/&quot; xmlns:feedburner=&quot;http://rssnamespace.org/feedburner/ext/1.0&quot; version=&quot;2.0&quot;&gt;&lt;channel&gt;&lt;title&gt;&lt;![CDATA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CNNWorld {
            get {
                return ResourceManager.GetString("CNNWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;rss xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;title&gt;DNES.BG: България&lt;/title&gt;
        ///    &lt;link&gt;http://www.dnes.bg/&lt;/link&gt;
        ///    &lt;description /&gt;
        ///    &lt;language&gt;bg&lt;/language&gt;
        ///    &lt;image&gt;
        ///      &lt;url&gt;http://85.14.28.164/d/images/rss_logo.png&lt;/url&gt;
        ///      &lt;title&gt;DNES.BG&lt;/title&gt;
        ///      &lt;link&gt;http://www.dnes.bg&lt;/link&gt;
        ///    &lt;/image&gt;
        ///    &lt;item&gt;
        ///      &lt;title&gt;Радев недоволен: Лобисти върнаха в началото конкурса за изтребителя&lt;/title&gt;
        ///      &lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DnesBG {
            get {
                return ResourceManager.GetString("DnesBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rss version=&quot;2.0&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///&lt;channel&gt;
        ///	&lt;title&gt;sportal.bg&lt;/title&gt;
        ///	&lt;link&gt;http://www.sportal.bg/&lt;/link&gt;
        ///	&lt;description&gt;Sportal BG&lt;/description&gt;
        ///	&lt;language&gt;bg&lt;/language&gt;
        ///	&lt;atom:link href=&quot;http://www.sportal.bg/uploads/rss_category_0.xml&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot; /&gt;
        ///	&lt;item&gt;
        ///		&lt;category&gt;БГ Футбол&lt;/category&gt;
        ///		&lt;title&gt;&lt;![CDATA[Венци Стефанов избухна: Един човек атакува съдиите - Краля слънце (видео)]]&gt;&lt;/title&gt;
        ///		&lt;link&gt;http://www.sportal.bg/news.php?news=685580 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SportalBG {
            get {
                return ResourceManager.GetString("SportalBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt;id&gt;tag:theregister.co.uk,2005:feed/theregister.co.uk/software/&lt;/id&gt;
        ///  &lt;title&gt;The Register - Software&lt;/title&gt;
        ///  &lt;link rel=&quot;self&quot; type=&quot;application/atom+xml&quot; href=&quot;https://www.theregister.co.uk/software/headlines.atom&quot;/&gt;
        ///  &lt;link rel=&quot;alternate&quot; type=&quot;text/html&quot; href=&quot;https://www.theregister.co.uk/software/&quot;/&gt;
        ///  &lt;rights&gt;Copyright В© 2017, Situation Publishing&lt;/rights&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;Team Register&lt;/n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheRegister {
            get {
                return ResourceManager.GetString("TheRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;rss version=&quot;2.0&quot;&gt;&lt;channel&gt;&lt;title&gt;Trafficnews.bg&lt;/title&gt;&lt;link&gt;https://trafficnews.bg/&lt;/link&gt;&lt;description&gt;Категория България&lt;/description&gt;&lt;language&gt;bg-bg&lt;/language&gt;&lt;copyright&gt;Copyright (C) 2017 Trafficnews.bg&lt;/copyright&gt;&lt;item&gt;&lt;title&gt;&lt;![CDATA[Болен мъж живее месеци наред на улицата в Смолян, социалните вдигат ръце СНИМКИ]]&gt;&lt;/title&gt;&lt;description&gt;&lt;![CDATA[Той е бил девет пъти в затвора]]&gt;&lt;/description&gt;&lt;category&gt;България&lt;/category&gt;&lt;guid&gt;https://trafficnews.bg/bulgaria/news/8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrafficNewsBG {
            get {
                return ResourceManager.GetString("TrafficNewsBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rss xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot; version=&quot;2.0&quot;&gt;
        ///&lt;channel&gt;
        ///&lt;atom:link href=&quot;https://www.vesti.bg/rss&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot;/&gt;
        ///&lt;title&gt;VESTI.bg&lt;/title&gt;
        ///&lt;description&gt;Български и световни новини от бизнеса и политиката. Наука, технологии и медии. Инциденти и произшествия, съдебна система. Любопитно за звездите.&lt;/description&gt;
        ///&lt;link&gt;http://www.vesti.bg/&lt;/link&gt;
        ///&lt;item&gt;
        ///&lt;title&gt;&lt;![CDATA[През 2018 г. учени ще търсят контакт с извънземни]]&gt;&lt;/title&gt;
        ///&lt;link&gt;https://www.vesti.bg/tehnolog [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VestiBG {
            get {
                return ResourceManager.GetString("VestiBG", resourceCulture);
            }
        }
    }
}
